# Generated by Django 4.0.5 on 2022-06-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeQnum', models.CharField(max_length=20)),
                ('fieldQnum', models.CharField(max_length=20)),
                ('departmentQnum', models.CharField(max_length=20)),
                ('websiteBaseUrl', models.CharField(max_length=100)),
                ('allOnePage', models.BooleanField(default=False)),
                ('file', models.FileField(default='/User/', upload_to='')),
            ],
        ),
    ]
