# Generated by Django 4.0.5 on 2022-06-08 18:38

import dataprep.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldQnum', models.CharField(max_length=20)),
                ('departmentQnum', models.CharField(max_length=20)),
                ('websiteBaseUrl', models.TextField(max_length=100)),
                ('allOnePage', models.CharField(max_length=1)),
            ],
        ),
    ]
