# Generated by Django 4.0.5 on 2022-06-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprep',
            name='filePath',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='dataprep',
            name='websiteBaseUrl',
            field=models.CharField(max_length=100),
        ),
    ]
