# Generated by Django 4.0.5 on 2022-06-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprep',
            name='collegeQnum',
            field=models.CharField(default='', max_length=20),
        ),
    ]
