# Generated by Django 4.0.5 on 2022-06-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprep', '0002_dataprep_filepath_alter_dataprep_websitebaseurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataprep',
            name='filePath',
        ),
        migrations.AddField(
            model_name='dataprep',
            name='file',
            field=models.FileField(default='/User/sprasad/', upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='dataprep',
            name='allOnePage',
            field=models.BooleanField(default=False),
        ),
    ]
