# Generated by Django 4.0.5 on 2022-06-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateWikidata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenureOrEmeritus', models.CharField(max_length=1)),
                ('destination', models.CharField(max_length=200)),
                ('sourceFile', models.FileField(default='/User/', upload_to='')),
            ],
        ),
    ]
