# Generated by Django 4.0.5 on 2022-06-15 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createwikidata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createwikidata',
            name='destination',
        ),
    ]
